### ISSUE TITLE
1inch bsc farming

### ISSUE THREAD

**Issue by ramiy** [cosmostation/defistation-web#12]
Can you add **1inch** farming on **BSC mainnet**?

https://1inch.exchange/#/dao/farming?network=56

**Comment by Booyoun-Kim** [comment]
@ramiy Hi. Please fill out the application form at this link. We will review yours ASAP 😃
https://forms.gle/SUPc87JiR8Nt4FMp7

**Comment by Booyoun-Kim** [comment]
@ramiy I checked your application. Did you receive API Key?

**Comment by ramiy** [comment]
1inch is not my project... I'm just one of your users and a liquidity provider for 1inch BSC.
