### ISSUE TITLE
wrong URL, no audit 

### ISSUE THREAD

**Issue by Kwaskoff** [cosmostation/defistation-web#4]
https://www.defistation.io/bdollarprotocol
![image](https://user-images.githubusercontent.com/15308024/107123712-145b6980-68b0-11eb-8b96-545cca96d726.png)
1. URL looks right, but inside another one https://github.com/anyswap/Anyswap-Audit/tree/master/SlowMist
2. I opened showing URL, but this has three audits of another project
![image](https://user-images.githubusercontent.com/15308024/107123771-8469ef80-68b0-11eb-8cce-bb3f32689152.png)
it's not audit of bdollar - right?

**Comment by Booyoun-Kim** [comment]
Hi @Kwaskoff 
Thank you for checking it. We will look into this audit in detail.

**Comment by Booyoun-Kim** [comment]
We have checked the audit link and we cannot find any audit of bdollarprotocol. Until the audit is confirmed, we uncheck the audit mark. Thanks.
